#!/bin/bash
set -e

cd $(dirname $0)/..

VERSION=${VERSION:?"VERSION not set"}
PACKAGE=${PACKAGE:?"PACKAGE not set"}
ARCH=${ARCH:?"ARCH not set"}

rm -rf ./dist/artifacts
mkdir -p ./dist/artifacts/

ARTIFACT_PATH="./dist/artifacts/strongswan-v${VERSION}${PACKAGE}-${ARCH}.tar.gz"

tar -cvzf "$ARTIFACT_PATH" $(find /usr/local \! -type d)
shasum -a 256  "$ARTIFACT_PATH" | awk '{print $1}' > "$ARTIFACT_PATH.sha256"
ls -lah "$ARTIFACT_PATH"*
