#!/bin/bash
set -e

cd $(dirname $0)/..

VERSION=${VERSION:?"VERSION not set"}
PACKAGE=${PACKAGE:?"PACKAGE not set"}
ARCH=${ARCH:?"ARCH not set"}

rm -rf ./dist/artifacts
mkdir -p ./dist/artifacts/

tar -cvzf ./dist/artifacts/strongswan-v${VERSION}${PACKAGE}-${ARCH}.tar.gz $(find /usr/local \! -type d)
ls -lah ./dist/artifacts/strongswan-v${VERSION}${PACKAGE}-${ARCH}.tar.gz
